#!/bin/sh

MODEL=$(cat /proc/device-tree/model)
X1PRO="X1"
X15G="5G"
T1="T1"
MMIFACENAME="mobile"
OPENWISPIP="172.16.0.1"
OPENWISPIFACE="nhwg0"

chmod +x /usr/bin/watchcat.sh
chmod +x /etc/init.d/watchcat

uci add watchcat watchcat
uci set watchcat.@watchcat[-1].pinghosts="8.8.8.8"
uci set watchcat.@watchcat[-1].pingsize="standard"
uci set watchcat.@watchcat[-1].unlockbands="1"

if echo "$MODEL" | grep -q "$X1PRO"; then
    if echo "$MODEL" | grep -q "$X15G"; then
        uci set watchcat.@watchcat[-1].period="15s"
        uci set watchcat.@watchcat[-1].pingperiod="5s"
        uci set watchcat.@watchcat[-1].mode="restart_iface"
        uci set watchcat.@watchcat[-1].interface="wwan0_1"
    else
        uci set watchcat.@watchcat[-1].period="5m"
        uci set watchcat.@watchcat[-1].pingperiod="5s"
        uci set watchcat.@watchcat[-1].mode="restart_iface"
        uci set watchcat.@watchcat[-1].interface="wwan0"
        uci set watchcat.@watchcat[-1].mmifacename="$MMIFACENAME"
        uci set system.led_wwan.dev="wwan0"
    fi
elif echo "$MODEL" | grep -q "$T1"; then
    uci set watchcat.@watchcat[-1].period="5m"
    uci set watchcat.@watchcat[-1].pingperiod="5s"
    uci set watchcat.@watchcat[-1].mode="restart_iface"
    uci set watchcat.@watchcat[-1].interface="wwan0"
    uci set watchcat.@watchcat[-1].mmifacename="$MMIFACENAME"
    uci set system.led_wwan.dev="wwan0"
fi

uci add watchcat watchcat
uci set watchcat.@watchcat[-1].pinghosts="8.8.8.8"
uci set watchcat.@watchcat[-1].pingsize="standard"
uci set watchcat.@watchcat[-1].mode="ping_reboot"
uci set watchcat.@watchcat[-1].period="5m"
uci set watchcat.@watchcat[-1].pingperiod="5s"
uci set watchcat.@watchcat[-1].forcedelay="10"

uci add watchcat watchcat
uci set watchcat.@watchcat[-1].pinghosts=$OPENWISPIP
uci set watchcat.@watchcat[-1].pingsize="standard"
uci set watchcat.@watchcat[-1].mode="restart_iface"
uci set watchcat.@watchcat[-1].interface=$OPENWISPIFACE
uci set watchcat.@watchcat[-1].period="1m"
uci set watchcat.@watchcat[-1].pingperiod="30s"

exit 0
