#!/bin/sh
MODEL="$(cat /proc/device-tree/model)"
X1PRO="X1"
X15G="5G"
T1="T1"

echo "Configuring $MODEL Network Hoist OpenWISP"

chmod +x /etc/openwisp/post-registration-hook
uci set openwisp.http.enabled='1'
uci set openwisp.http.url='https://mgmt.networkhoist.com/'
uci set openwisp.http.shared_secret='QRoBWH4oSX7mwzpcRhgK2qD2IzZjmgoI'
uci set openwisp.http.verify_ssl='0'

if [[ "$MODEL" == *"$X1PRO"* ]]; then
    uci set openwisp.http.default_hostname='TelcoX1Pro'
    if [[ "$MODEL" == *"$X15G"* ]]; then
        uci set openwisp.http.tags='x1pro5G pppoeserver nhwg0'
        uci commit openwisp
        exit 0
    else
        uci set openwisp.http.tags='x1pro pppoeserver nhwg0'
        uci commit openwisp
        exit 0
    fi
fi

if [[ "$MODEL" == *"$T1"* ]]; then
    uci set openwisp.http.tags='telcot1 accesspoint nhwg0'
    uci set openwisp.http.default_hostname='TelcoT1'
    uci commit openwisp
    exit 0
fi
